[package]
name = "feige_fiat_shamir"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4.3", features = ["rand"] }
num-traits = "0.2.16"
rand = "0.8.5"
num-primes = "0.3.0"
