[package]
name = "elliptic_curve"
version = "0.1.0"
edition = "2021"

[lib]
name = "elliptic_curve"
path = "src/lib.rs"

[dependencies]
finite_field = { path = "../finite_field" }
num-bigint = { version = "0.4.3", features = ["rand"] }
num-traits = "0.2.16"
sha2 = "0.10.8"
rand = "0.8.5"
